name: Build and deploy PHP app to Azure Web App - gestionnaire-des-apprentis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        run: test -f composer.json && echo '::set-output name=files_exists::true' || echo '::set-output name=files_exists::false'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        run: mv release.zip $GITHUB_WORKSPACE/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        run: mv $GITHUB_WORKSPACE/release.zip .

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_SERVICE_PRINCIPAL }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: 'Deploy to Azure Web App'
        run: |
          az webapp deployment source config-zip --resource-group <resource-group-name> --name <app-name> --src release.zip
